### ISSUE TITLE
Pokémon Purple (Pokémon fangame)

### ISSUE THREAD

**Issue by The4thPlayer** [Universal-Team/db#145]
### Title

Pokémon Purple Version

### System(s)

3DS

### Categories

Game

### Unique ID(s)

000400000430C900

### Long description

This is a simple Pokémon fan-game created in the style of Generation 1; (The first line of Pokémon games.)
using GB Studio and New Super Ultimate Injector.
There is no special installation required, as it is a .cia

### Author

FlameTheGamer

### Short description

A very short Generation 1 style Pokémon Fangame made with GB Studio and New Super Ultimate Injector.

### Creation date

June 21, 2023

### Last update date

Augest 8/9/2023

### Download page link

https://github.com/The4thPlayer/Pokemon-Purple/releases/tag/Release

### Version number

0.0.2

### Version title

Version 0.0.2

### Download link(s)

https://github.com/The4thPlayer/Pokemon-Purple/releases/tag/Release

### Developer permission

- [x] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by Golem642** [comment]
Hello, unfortunately websites like gamejolt and itch.io have a setup of temporary links for downloads, which mean we currently can't download it directly with Universal Updater.
If you have the permission of the creator, you can setup a GitHub/GitLab or anything that you'd like (for example a cloud storage) containing the latest release of the game and send the link here, this does mean that if you want to have the games updates (if there will be any) directly onto Universal Updater you need to manually do the update yourself (which is why i recommend using Github, and simply putting the latest release in the releases tab will do the rest automatically)

**Comment by The4thPlayer** [comment]
Ahh ok,
I'd better make a repo then.

**Comment by The4thPlayer** [comment]
here
https://github.com/The4thPlayer/Pokemon-Purple/releases/tag/Release

**Comment by The4thPlayer** [comment]
btw how do i add a thumbnail for it

**Comment by Golem642** [comment]
you can link me the app icon, banner on the HOME menu, or screenshots here if you will

**Comment by The4thPlayer** [comment]
the banner just uses the default virtual console one, (albeit slightly customized) but i think thats already built into the .cia
heres the icon: https://m.gjcdn.net/fireside-post-image/400/27841165-xm2u2ac7-v4.webp
and here are 3 screenshots: https://m.gjcdn.net/game-screenshot/300/23943986-ll-citwdxjq-v4.webp https://m.gjcdn.net/game-screenshot/300/23943987-ll-hvcvafvs-v4.webp https://m.gjcdn.net/game-screenshot/300/23943990-ll-jkkfftrs-v4.webp

**Comment by Golem642** [comment]
> heres the icon: https://m.gjcdn.net/fireside-post-image/400/27841165-xm2u2ac7-v4.webp
I meant the icon of the app on a 3DS, otherwise it won't fit in U-U

> and here are 3 screenshots: https://m.gjcdn.net/game-screenshot/300/23943986-ll-citwdxjq-v4.webp https://m.gjcdn.net/game-screenshot/300/23943987-ll-hvcvafvs-v4.webp https://m.gjcdn.net/game-screenshot/300/23943990-ll-jkkfftrs-v4.webp
I'm not sure but i think these need to be in the 3ds image size, like you are playing the game on 3ds, you open up rosalina menu, and you take some screenshots. And then you combine them with an image editor, see other screenshots on the site for references

**Comment by The4thPlayer** [comment]
but how do i find that? take a picture with its camera and adjust the pics accordingly using photoshop?

**Comment by The4thPlayer** [comment]
ohhh ok. that IS the icon file i used though, and im not sure what size i would need to crop it to

**Comment by The4thPlayer** [comment]
also here are the screenshots
https://m.gjcdn.net/fireside-post-image/400/27842891-mcusde2h-v4.webp
https://m.gjcdn.net/fireside-post-image/400/27842892-5y9kwb6n-v4.webp
https://m.gjcdn.net/fireside-post-image/400/27842893-ll-uwjxf3ja-v4.webp

**Comment by Golem642** [comment]
The icon must be 48x48 pixels, and I've just got information that only the gb file is allowed on the Universal db since the CIA version is using Nintendo's Virtual Console which is proprietary software.

**Comment by The4thPlayer** [comment]
So if I make an inject using a different emulator (like virtuaNES) then THAT could be submitted?

**Comment by The4thPlayer** [comment]
I just checked and apparently I can inject it using Gambette. Would that be accepted?

**Comment by Golem642** [comment]
I'm sorry i don't know what is Gambette, i can't find anything on the web either. If that is homebrew software and not proprietary then yes it will be accepted

**Comment by The4thPlayer** [comment]
I believe it is a Retroarch emulator, that allows me to create an inject of the rom without using the official Virtual Console. (you don't actually need retroarch to use it, it just runs on it)

**Comment by The4thPlayer** [comment]
I'd better just test the .cia really quick though.

**Comment by The4thPlayer** [comment]
https://github.com/The4thPlayer/Pokemon-Purple/releases/tag/Also-Release

**Comment by The4thPlayer** [comment]
here they are, sorry for posting so much btw
https://m.gjcdn.net/fireside-post-image/400/27846135-4akaf3md-v4.webp
https://m.gjcdn.net/fireside-post-image/400/27846136-cybcabpn-v4.webp
https://m.gjcdn.net/fireside-post-image/400/27846137-uj9ptnfk-v4.webp

**Comment by The4thPlayer** [comment]
Just checking but is the Gambatte version acceptable?

**Comment by Golem642** [comment]
Sorry it's been a bit since I've touched the PR. It is acceptable but it'll be better if you included in the releases both the Gambatte version and the original gb file, that way people who don't want to use Gambatte can use the gb file with the emulator of their choice. And for lazy people or some that don't understand a lot, they can still install the Gambatte CIA and play the game

**Comment by The4thPlayer** [comment]
Ok, I will add it to the release
