### ISSUE TITLE
Website not automatically redirecting to HTTPS

### ISSUE THREAD

**Issue by Zachary-Rude** [Universal-Team/db#155]
There's currently a **major** issue with the [db.universal-team.net](https://db.universal-team.net) website where it does **not** take you to the HTTPS version unless you explicitly type `https://` at the beginning of the URL. Please fix this issue, as it's a very major bug.

**Comment by Zachary-Rude** [comment]
Also, why is there an `index.md` file but no `index.html`?

**Comment by Epicpkmn11** [comment]
This is intentional so the website can be used on 3DS, it doesn't really hurt anything on PC. If you're worried about accessing HTTP sites I recommend enabling HTTPS only mode if you use Firefox or I think plugins exist for other browsers.

There is no index.md on the actual site, it's Markdown in GitHub because that simplifies the site.
