### ISSUE TITLE
HALO

### ISSUE THREAD

**Issue by HydraCatYT** [Universal-Team/db#16]
**HALO Revamped V1.11**

**3DS Old + New 3DS**

**Quake**

**https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Freplayers.org%2Fwp-content%2Fuploads%2F2019%2F08%2FHalo-revamped-coverart-dreamcast.jpg&f=1&nofb=1**

**https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Freplayers.org%2Fwp-content%2Fuploads%2F2019%2F08%2FHalo-revamped-coverart-dreamcast.jpg&f=1&nofb=1**

**This QUAKE Mod made 75% by TCPIXEL 25% by CollinScripter Uploaded by Linguini5346 **

**none ;(  **

**https://github.com/CollinScripter/Revamped3DS/releases/tag/V1.11**

**75% by TCPIXEL 25% by CollinScripter**

**A HALO style QUAKE Mod**

**https://github.com/CollinScripter/Revamped3DS**

**2010**

**Aug 5, 2017,**

**https://github.com/CollinScripter/Revamped3DS**

**Why?**

**https://github.com/CollinScripter/Revamped3DS/releases/tag/V1.11**

**V1.11**

**CollinScripter RECONTINUED VERSION**

**Aug 3, 2017,**

**none**

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by CollinScripter** [comment]
> I am the app developer or have permission from the app developer to make this request

I'd just like to note, because why not, that I was never contacted about this. My discord is in my GitHub bio, it really isn't that hard to contact me, and I highly doubt you asked TCPixel.
I personally am absolutely fine with it being on the database, but really you would need to contact TCPixel, the person who developed Halo Revamped for the Nintendo 3DS. Although I'd expect he'd be fine with it, given he never had issue with me hosting it on GitHub without permission.

Mostly I would like to request that I not be listed as the main author of the application. What I did to the application was a few tweaks, namely
- O3DS support for version 1.1
- Added an option to disable 3D (mostly because my 3D slider was broken and homebrew doesn't care about parental controls)
- A CIA build that wasn't the default title ID from some random rsf off the internet.
 
EVERYTHING ELSE was from TCPixel (for Revamped), MasterFeizz (for ctrQuake), and Flaming Ice (for Halo Solitude).
If you're going to put it on the database, please put just TCPixel, or include those other names as well.

**Comment by Epicpkmn11** [comment]
Ah, I see, just changed the author to just TCPixel. If someone wants to ask him and he'd prefer it not be on here I can remove it, otherwise for now I'll keep it on 👍

(I did just TCPixel as I'd rather the author string not get *too* long, but if anyone else has input I'm happy to change it)

@HydraCatYT please actually do check with the developers if you can if you make any more requests. I don't expect many people to have problems as it's not like we even rehost the files and I've done my best to try make it easy to find the official websites, source code, docs, etc from our site, but it's still nice to ask.

**Comment by HydraCatYT** [comment]
I will check if I have the rights also I will try to find contact with TCPpixel I will keep up to date with screenshots if i get contact with him
