### ISSUE TITLE
Several apps including FBI reloaded were destroyed by TWLBot

### ISSUE THREAD

**Issue by Anonymous941** [Universal-Team/db#255]
In 2d785a6205a6d877b0c69abb85ee297ee44dbaf5, these apps were removed somehow by TWLBot:

* **FBI reloaded**(!)
* Starlight3DS

And non-English languages for these apps were removed:

* Luma3DS
* FBI
* ThirdTube
* GodMode9
* ThirdTube

What's going on??  Is TWLBot having a hard time parsing forks for some reason?

**Comment by Anonymous941** [comment]
How is FBI Reloaded is a low-quality fork?

**Comment by eip618** [comment]
hello cooolgamer alt

**Comment by Naim2000** [comment]
@Anonymous941 
> How is FBI Reloaded is a low-quality fork? And Starlight3DS adds a lot of useful features

FBI-Reloaded just adds a dark theme(?) and increases the download timeout for Remote install (🏴‍☠️)

Starlight3DS? It adds a lot of features. Not necessarily useful. Nobody needs a
`Press A + B + X + Y + Start to instantly reboot the console.`
Nor a
`Added loading of external decrypted otp from luma/otp.bin` (unless you're ban evading!)
It's mostly niche, and additionally, most of these are simply combined from other Luma forks

**Comment by Anonymous941** [comment]
Yes, those features are mostly useless, but some aren't, such as permanent brightness recalibration, software home button, streaming and quick switching of NDS tweaks

**Comment by fox8091** [comment]
@Anonymous941 Some of the features (especially instant reboot and extended screen brightness) are *actively harmful* to users consoles. If you want to use it, nobody's stopping you, but it shouldn't be offered through the default repo.

**Comment by MisterSheeple** [comment]
I would argue that FBI-Reloaded is necessary to have. Dark mode is an accessibility change that increases readability for those who have trouble with reading in light mode. Increasing the download timeout is a good thing for installing larger homebrews. Neither of these are unnecessary changes.

Where can these guidelines be read in detail?

**Comment by NightScript370** [comment]
Your arguments are nullified because the larger Homebrew downloading isn't prevented by the timeout, and the light theme vs dark theme is moot when the device is an LCD and not OLED.
Guidelines can be found in the GitHub folder

**Comment by MisterSheeple** [comment]
My arguments are not nullified by your strawman argument.

Longer timeout is inherently a very good thing for people with poor internet connections.

Dark mode is not nullified by it being LCD, because as I said, it's for accessibility and better readability. It can reduce eyestrain and make things readable for people with vision problems (also including some types of colorblindness), so having dark mode as an option is very important for user accessibility.

**Comment by fyredragon69** [comment]
> Longer timeout is inherently a very good thing for people with poor internet connections that frequently drop out.

if this is such an issue, these users should download the homebrew on another computer and copy it over instead
> Dark mode is not nullified by it being LCD, because as I said, it's for accessibility and better readability. Even on LCD, it can reduce eyestrain and make things readable for people with vision problems (also including some types of colorblindness), so having dark mode as an option is very important for user accessibility.

fbi has been like this for _years_. why would we change it now? it's pretty much complete software, the changes proposed aren't enough to unarchive and have everyone ask if it's okay to update

**Comment by MisterSheeple** [comment]
> if this is such an issue, these users should download the homebrew on another computer and copy it over instead

This isn't the kind of thing where you can predict how outside factors will work in a hypothetical scenario because it'll differ for everyone, so you can only design stuff like this based on inside factors. Trying to predict anything beyond that is a fool's errand because you will never be able to predict what someone's situation will be.

Also if FBI has inbuilt theming support, how come it doesn't ship with a dark theme?

**Comment by Anonymous941** [comment]
> it's pretty much complete software, the changes proposed aren't enough to unarchive and have everyone ask if it's okay to update

Who said anything about asking everyone to update?
