### ISSUE TITLE
TheXTech

### ISSUE THREAD

**Issue by Trickiy** [Universal-Team/db#263]
### Title

TheXTech (Alpha build)

### System(s)

3DS

### Categories

Game

### Image link

https://github.com/TheXTech/TheXTech/blob/main/resources%2Fwiiu%2Fwuhb-splash.png

### Long description

This is a direct continuation of the SMBX 1.3 engine. Originally it was written in VB6 for Windows, and later, it got ported/rewritten into C++ and became a cross-platform engine. It completely reproduces the old SMBX 1.3 engine (aside from its Editor), includes many of its logical bugs (critical bugs that lead the game to crash or freeze got fixed), and also adds a lot of new updates and features.

### Screenshots

![2024-08-27_20-56-16 278_top](https://github.com/user-attachments/assets/3b16d228-f572-469d-8a22-e67a2d2e52bb)
![2024-08-27_20-56-33 703_top](https://github.com/user-attachments/assets/71b9cd15-59ff-4189-a37e-5d59c77dffb1)
![2024-08-27_20-56-58 853_top](https://github.com/user-attachments/assets/bc2807a3-80ea-4c08-9a21-cc45d1fa2c4c)
![2024-08-27_20-58-41 895_bot](https://github.com/user-attachments/assets/d4d160d8-4268-4a72-94a8-80a59a827bc4)

### GitHub repository of the app

https://github.com/TheXTech/TheXTech

### Author

Wohlstand, ds-sloth

### Short description

The full port of the SMBX engine from VB6 into C++ and SDL2, FreeImage and MixerX

### Version number

1.3.7-dev

### Version title

Alpha

### Download link(s)

Main alpha build (Nightly)
https://builds.wohlsoft.ru/3ds/thextech-3ds-main.zip
smbx 1.3 asset pack
https://builds.wohlsoft.ru/3ds/assets-smbx13-3ds.zip
Adventure of Demo asset pack
https://builds.wohlsoft.ru/3ds/assets-aod-3ds.zip

### Other notes

Assets are required once.

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request; my request is compliant with the [Universal-DB guidelines](https://github.com/Universal-Team/db/blob/da0f7076fa5632294af0c597efe315bcc86acab4/CONTRIBUTING.md#app-requests)

**Comment by ds-sloth** [comment]
Co-lead developer of the engine (and 3DS maintainer) here, happy to answer any questions.

Wiki: https://github.com/TheXTech/TheXTech/wiki
Website: http://wohlsoft.ru/projects/TheXTech/
Creation date: this dates back to https://github.com/ds-sloth/TheXTech3DS/ from May 2021, but the 3DS port has been mainline since Dec 2022.
Update date: at least one commit a week.

Notes on the version: this is off our main branch which is moderately unstable. I'm currently preparing for our 1.3.7 release freeze which will start with a beta, but there are still two minor features to go, and plenty of bug-testing. Trickiy has been very helpful in finding bugs on 3DS, and as long as Universal-DB users are aware that this is alpha-quality, I will really appreciate their help also.

Our current stable release doesn't support the 3DS's native resolution, so I can't recommend it, but eventually I would like to offer separate stable and dev branches on Universal-DB.

**Comment by Epicpkmn11** [comment]
Sorry for how slow I've been maintaining this recently, added in 2aa4d6b957e93ec7794d9fe43ba57b7d95649c1e
