### ISSUE TITLE
Wilson(BROWSERHAX)

### ISSUE THREAD

**Issue by wicorn29** [Universal-Team/db#36]
**Name of the app**
Wilson's Browserhaxx

3ds
**3ds and 2ds(s)**

Hacks

https://www.mediafire.com/file/4c7jvukmrf5exju/CI7_WiiU_InternetBrowser_CMM_small.png/file

https://www.mediafire.com/file/nied71zluyn3rat/attachment_76464214.png/file

None!

None

**GitHub repository of the app**

Wilson Corn

Use BROWSERHAX and MAKE SHOURE YOU HAVE FALLOWED THE GUIDE ON: 3ds.hacks.guide! (THIS REPLACES THE qr CODE!)

None...

Unknown

I had no update!

none

none

https://www.mediafire.com/file/brdjbuctluy3koc/BROWSERHAX.cia/file

0.0.0.1

None

No update!

**Download link(s)**
[.CIA](https://www.mediafire.com/file/brdjbuctluy3koc/BROWSERHAX.cia/file)

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
fyi I don't think Universal-Updater can download from MediaFire so using a GitHub release or other download method that lets you directly link the file instead of a download page would be preferred.

Also... What exactly is this? You can't install CIA files before already having CFW so I don't see how a CIA would be related to browserhax...

**Comment by NightYoshi370** [comment]
Closed, due to a lack of response and failure to explain properly.
