### ISSUE TITLE
Multiple wrong items in DB (-unistore representation)

### ISSUE THREAD

**Issue by vargaviktor** [Universal-Team/db#8]
Hi,
I used the Universal Updater on 3DS (v3.0.0), i found several bugs:
* opentitus
each download finishes with delete error message
* eduke cia donwload
kills Universal Updater, app closes, and goes back to the Home screen

I think these are some kind of db bugs.

**Comment by Epicpkmn11** [comment]
The eduke downloads were a simple problem, I did `"Owner/Repo"` instead of `"masterfeizz/EDuke3D"` in the downloads 🤦‍♀️
So they'll be fixed in ~6 hours when it updates the UniStore.

The OpenTitus downloads however seem to be libarchive bugging out so that can't be easily fixed... It only seems to affect the new 3DS versions, so I could just have it download the latest ones... but those say
> ONLY for old3DS users, these builds use low frequency audio.
> Worse audio quality, but near full speed.

on the release so that's not ideal... Not sure what to do for that right now...

**Comment by Epicpkmn11** [comment]
OpenTitus is fixed by the latest UU nightly since we've updated to libarchive v3.5.1
