### ISSUE TITLE
requesting to add chainload

### ISSUE THREAD

**Issue by itsjoeboi** [Universal-Team/db#81]
### Title

chainload

### System(s)

3DS

### Categories

Utility, Save Tool

### Image link

https://i.postimg.cc/TPmfBFfw/banner.png

### Icon link

https://i.postimg.cc/SQLjn20s/icon.png

### Long description

<h1>Chainload</h1>
<h3>a App to chain your system to mii's and to the firmware</h3>
<p>with just a click of a button</p>

### Screenshots

https://i.postimg.cc/qM5trfVX/screen-1.png

### Author

BoiFemboy

### Short description

Chain your mii's and firmware!

### Source code link

https://gist.github.com/itsjoeboi/c56e6d4f10b4704f53b81d1e9e0abb1f

### Creation date

16/5/2022

### Last update date

20/5/2022

### Download page link

https://github.com/itsjoeboi/chainload-download

### Version number

V1.3.2

### Version title

ChainUpdate

### Download link(s)

github: https://github.com/itsjoeboi/chainload-download

google drive: https://drive.google.com/file/d/1ACDfQ86pVo4E0NfzCHngywu2UkeCajRf/view?usp=sharing

### Other notes

you need hbr to open it there is curently no CIA of the app because i still haven't found a way to build a cia

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
What's the purpose of this supposed to be? It seems to basically just be an example app that opens the Mii picker and prints out some text... Is it supposed to actually "chainload" into anything or is it supposed to just return to the HBL? As per the [contributing guidelines](https://github.com/Universal-Team/db/blob/master/CONTRIBUTING.md) I'm going to close this as lacking in functionality. If you expand it though you can feel free to reopen the issue.

Also, it looks like your source code doesn't match up with the actual binary, the source doesn't even have the Mii picker and such. I'd recommend putting your source in an actual repo that way you can have all the proper structure with the Makefile and such so that someone else could easily build it and then use the releases feature for the downloads instead of putting them in the repo.
