### ISSUE TITLE
HTTP Server for the 3ds

### ISSUE THREAD

**Issue by dimaguy** [Universal-Team/db#94]
### Title

3ds-httpd

### System(s)

3DS

### Categories

Utility

### Image link

https://github.com/dimaguy/3ds-httpd/raw/master/assets/banner.png

### Icon link

https://github.com/dimaguy/3ds-httpd/raw/master/assets/icon.png

### Long description

# A Web Server for the 3DS
A flexible httpd server capable of handling sdcard file reads, crypto operations, system requests and raw memory operations.
(Documentation is underway)

### Screenshots

(Unavailable at the moment)

### GitHub repository of the app

https://github.com/dimaguy/3ds-httpd

### Author

Thog, SciresM, Dimaguy

### Short description

Web Server for the 3DS

### Download link(s)

https://github.com/dimaguy/3ds-httpd/suites/8317630915/artifacts/365299705

### Other notes

This is mostly a draft request, will add remaining pieces as I go

### Developer permission

- [X] I am the app developer or have permission from the app developer to make this request

**Comment by Epicpkmn11** [comment]
fyi artifact links don't work for non-signed in users, and thus don't work in UU. Also nightly.link isn't working quite properly because you have it set to `workflow_dispatch` instead of automatic, so I'd have to hardcode it to <https://nightly.link/dimaguy/3ds-httpd/actions/artifacts/365299705.zip>.

I'd recommend either making proper (pre-)releases as that works best with Universal-DB and setting Actions to run on push.
